blinkk/amagaki

.eslintrc.json
src/builder.ts
src/cache.ts
src/collection.ts
src/commands/build.ts
src/commands/serve.ts
src/document.ts
src/index.ts
src/pod.ts
src/renderer.ts
src/router.ts
src/server.ts
src/utils.ts

Uses the default sorting options for `sort-imports`.
See https://eslint.org/docs/rules/sort-imports

Updating the import orders to be consistent.

---

package.json
src/builder.ts

This shaves a few seconds off the 5,450 file build. (From 13/14 sec to 11/12 sec.)

Use async for builder file operations

---

example/amagaki.js
example/content/pages/index.yaml
example/plugins/example.js
example/views/partials/debug.njk
src/document.ts
src/plugins.ts
src/plugins/nunjucks.ts
src/plugins/yaml.ts
src/pod.ts
src/templateEngine.ts
src/utils.ts

Add a template engine manager and move the built-in template engines into build-in plugins.
Moved the yaml custom types into a built-in yaml plugin.

Convert from `Renderer` to `TemplateEngine`.

---

package-lock.json
package.json
src/builder.ts
src/commands/build.ts
src/plugins.ts
src/profile.ts

Updating the console output when running profiling to make it look nicer and easier to read.
Current output example:
```
Build command took 88.3ms (1.00% called 1x, 88.3ms each)
Document fields localization took 5.0ms (0.06% called 35x, 0.1ms each)
File exists took 2.1ms (0.02% called 133x, 15.84µs each)
File read took 1.3ms (0.02% called 20x, 66.96µs each)
Hook: createTemplateEngine took 0.1ms (0.00% called 1x, 0.1ms each)
ExamplePlugin hook: createTemplateEngine took 20.73µs (0.00% called 1x, 20.73µs each)
NunjucksPlugin hook: createTemplateEngine took 54.87µs (0.00% called 1x, 54.87µs each)
Hook: createYamlTypes took 0.2ms (0.00% called 1x, 0.2ms each)
ExamplePlugin hook: createYamlTypes took 28.44µs (0.00% called 1x, 28.44µs each)
YamlPlugin hook: createYamlTypes took 0.1ms (0.00% …
```

Improve profiling console output.

---

package-lock.json
src/document.ts
src/router.ts

Allows for using `${doc.collectionPath}` in url formatting.
For example:
Given a collection (`/content/pages/_collection.yaml`) with a page in a
sub directory (`/content/pages/sub/other/page.yaml`) then `doc.collectionPath`
would be `/sub/other`.
When used in a `$path: /${doc.collectionPath}/${doc.basename}/` for the collection `$path`.
the `/content/pages/sub/other/page.yaml` url path would become `/sub/other/page/`.

Collection path for documents to reference relative collection path.

---

src/document.ts
src/pod.ts

The fallback to use pod level locales when a document and collection do not define `locales` of their own was running into issues where the `Locale` set included `string` locale ids instead of `Locale` objects.

Pod level locales need to be `Locale` objects not `string`s.

---

fixtures/basePath/amagaki.js
fixtures/basePath/content/about.njk
src/fixtures.test.ts
src/pod.test.ts
src/pod.ts
src/router.ts

Work on #49
NOTE: This is currently implemented as `pod.basePath` so it's convenient for use in the `_collection.yaml` and `$path` settings. LMK if you think we should nest this somewhere else.
This also updates the fixture test runner to skip empty directories (that might get left in a git workspace when switching branches).

Add pod.basePath

---

fixtures/static/src/static/file.txt
src/static.test.ts
src/static.ts

Should we make `fingerprint` a getter or a callable? If a callable, we may be able to extend it (i.e. you could request the md5 instead of the default sha256). That's how Hugo works FWIW.
Also, should we make `exists` a callable (ie. `exists()`) because it has to make the fs operation?

Add fingerprint and exists method to StaticFile. Fixes #52

---

README.md
example/content/pages/about.yaml
example/content/pages/index.yaml
example/content/pages/routes.yaml
example/content/partials/header.yaml
example/views/base.njk
fixtures/simple/content/pages/about.yaml
fixtures/simple/content/pages/index.yaml
fixtures/simple/content/pages/routes.yaml
fixtures/simple/content/partials/header.yaml
fixtures/simple/views/base.njk
fixtures/yamlTypes/amagaki.js
fixtures/yamlTypes/content/index.yaml
fixtures/yamlTypes/content/pages/index.yaml
fixtures/yamlTypes/content/pages/page.yaml
fixtures/yamlTypes/content/posts/2019-01-06.md
fixtures/yamlTypes/content/posts/2021-08-08.md
fixtures/yamlTypes/src/static/file.txt
package.json
src/document.ts
src/plugins/yaml.test.ts
src/plugins/yaml.ts
website/content/index.yaml
website/content/partials/footer.yaml
website/content/partials/header.yaml

This PR updates the syntax around Amagaki to be consistent (or, as close to as consistent and useful as possible), by cementing a concept called "pod functions".
"Pod functions" are basically the usage of (what we'll call) the "Pod API" – all the directly callable, useful functions on the primary "pod" object.
I think this concept is generally accessible (by way of docs), and readable, and more understandable than our historical concepts of `!g.doc` (and similar) in templates and YAML files in Grow. Since the syntax is as close as possible to directly calling the function on the main pod object, usage should be understandable across all parts of Grow.
In this PR I implement all the YAML types for the pod functions outlined here: …

Implement updated YAML types

---

src/commands/serve.ts
src/index.ts

Allows for `amagaki server --port 8888` ability for providing a port for the server to run on.
Help shows as:
```
Options:
--port <number>  development server port (default: "8080")
```

Add option to `serve` command for port.

---

src/document.ts
src/router.ts
src/server.ts

When building the documents on the dev server or in a preview server setting the build can pass along the request from express to allow the templates to be customized based on things like query params.
An example use case would be the 'help' text to show the partial and option information. Instead of needing to hide it with css, the template can use the request params to determine if the help information should even be rendered.

feat: Add request to the route building.

---

fixtures/sampleRouteProvider/amagaki.ts
fixtures/sampleRouteProvider/views/base.njk
src/builder.ts
src/document.ts
src/router.test.ts
src/router.ts

- Adds a sample custom route provider showing how to extend Amagaki with custom routes (e.g. from a database)
- Renames `Route` property `path` to `podPath` for correctness
- Uses html as the default route content type for developer ergonomics

fix: rename route.path to route.podPath and add sample provider

---

src/plugins/nunjucks.ts
src/profile.ts

When used with a Nunjucks global that invokes the timer, we get the following result with this:
```
┌─────────────────────────────────────────┬──────────┬─────────────────┬─────────────────────────────────────────────────┐
│ Templates                               │        % │            Time │ Stats                                           │
│ /views/base.njk                         │ 1085.26% │ 23 sec, 377.0ms │ 22 calls, 1 sec, 987.0ms max, 1 sec, 62.6ms avg │
│ /views/partials/image-with-text.njk     │   21.24% │         457.5ms │ 40 calls, 19.5ms max, 11.4ms avg                │
│ /views/partials/centered-video.njk      │    4.07% │          87.6ms │ 8 calls, 16.9ms max, 10.9ms avg                 │
│ /views/partials/feature-touts.njk       │    3.34% │          72.0ms │ 4 calls, …
```

feat: add support for per-template profiling #25

---

packages/amagaki-plugin-page-builder/src/page-builder.ts
packages/amagaki-plugin-page-builder/src/partial-preview.test.ts

Background:
1. `og:site_name` is an optional tag, but recommended (https://ogp.me/)
2. Social sites will use the `<title>` tag as a fallback if `og:title` is missing
3. IMDB, the example used on the OGP website, includes the site name in both the title tag and og:title on there actual site (but not in the example on ogp.me)
4. FB doesn't use/show og:site_name in the share dialog (https://developers.facebook.com/support/bugs/1153386624699119/?comment_id=223306658072032)
It seems like the general consensus is the `og:site_name` is a nice-to-have, but not really used by social sites. General practice is to make the `og:title` and `title` consistent, as they both are meant to represent the title of the current page. It's also common SEO practice to include the site name in the page title, but …

feat: support appended site name in og:title

---

packages/amagaki/src/document.ts

Currently if the document path is null it defaults to the collection path. But if you try to use
a null value for the path `$path: ~` then it ignores that and uses the collection.

fix: allow for setting the document path to null to disable

---

package-lock.json
package.json
packages/amagaki-plugin-page-builder/example/content/pages/index.yaml
packages/amagaki-plugin-page-builder/example/views/partials/hero.njk
packages/amagaki-plugin-page-builder/package.json
packages/amagaki-plugin-page-builder/src/ui/attribute-highlighter.ts
packages/amagaki/package.json
packages/create-amagaki/package.json
packages/create-amagaki/src/utils.ts

- Add `querySelector` key to each a11y attribute to make sure the labels only show on `img` elements

fix: alt text will only show once on a11y highlighter

---

package-lock.json
packages/amagaki/src/builder.test.ts
packages/amagaki/src/document.ts
packages/amagaki/src/plugins/nunjucks.ts

Switches out the render functions in the nunjucks plugin to use async functions. Removes some of the nested callbacks to make the logic simpler.

fix: Update nunjucks to use async for render functions.

---

packages/amagaki/src/plugins.ts
packages/amagaki/src/plugins/nunjucks.ts

Updates the afterRender hook to not be async since it needs to use the results of the previous plugin to make the next set of changes.

fix!: Change `afterRender` hook to be a sync trigger.

---

packages/amagaki/src/profile.ts

Since the threshold reporting doesn't really give anything actionable move it behind the normal profiling flag.

fix: Remove extra threshold reporting to clean up default builds.

---

package-lock.json
packages/amagaki/package.json
packages/amagaki/src/plugins/nunjucks.ts

The 5.0.0 version of marked doesn't default to mangled email addresses and separates into a separate plugin.

feat: Use mangled plugin for email addresses

---

.github/workflows/test-amagaki.yml
packages/amagaki/src/plugins.ts

When implementing `PluginComponent`, we're currently unable to include required props in the configuration, ie. all props must use the optional modifier `?`
```
export interface RandomConfig {
prop1?: string;
prop2?: string;
prop3?: string[];
}
export class RandomPlugin implements PluginComponent {
static register(pod: Pod, config: RandomConfig): RandomConfig {
pod.plugins.register(RandomPlugin, config ?? {});
return config;
}
}
```
The configuration is inheriting from PluginComponent's config (`Record<string, any>`) and it currently does not support required props. This change makes the PluginComponent interface generic, and should allow for non-optional props on the child component configs, .ie.
```
export interface RandomConfig {
prop1: string;
prop2: string;
prop3: string[];
}
export …
```

fix: Update PluginConstructor to use a generic constructor signature
